'use strict';

// Naming: ACTION_ENTITY_RESULT
export default {
    ADD_TODO: 'ADD_TODO',
    CLEAR_ALL: 'CLEAR_ALL',
    COMPLETE_TODO: 'COMPLETE_TODO',
    TOGGLE_MODAL: 'TOGGLE_MODAL',
    FETCH_TEST: 'FETCH_TEST',
    SEND_CLAIM: 'SEND_CLAIM'
};
