# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-18 22:48
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='bribe',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='moderation',
            field=models.CharField(choices=[('not_moderated', 'Not moderated'), ('suspicious', 'Suspicious'), ('anonymous', 'From anonymous'), ('valid', 'Moderated'), ('markers', 'Non-verified markers')], default='not_moderated', max_length=50),
        ),
        migrations.AlterField(
            model_name='moderator',
            name='show_claims',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('not_moderated', 'Not moderated'), ('suspicious', 'Suspicious'), ('anonymous', 'From anonymous'), ('valid', 'Moderated'), ('markers', 'Non-verified markers')], default='not_moderated,suspicious,anonymous,valid', max_length=200),
        ),
    ]
