# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-17 16:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0002_auto_20160218_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 3, 17, 16, 6, 46, 664182)),
            preserve_default=False,
        ),
    ]
