# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0003_organization_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
