# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 22:34
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('claim', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polygon',
            fields=[
                ('polygon_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('shape', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('centroid', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=800, null=True)),
                ('level', models.IntegerField(choices=[(0, 'Root polygon'), (1, 'Regions of country'), (2, 'Subregions or big sities'), (3, 'Towns or districts of city'), (4, 'Houses')], default=4)),
                ('is_default', models.BooleanField(default=False)),
                ('zoom', models.IntegerField(blank=True, null=True)),
                ('layer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geoinfo.Polygon')),
                ('organizations', models.ManyToManyField(to='claim.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='Uploader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_file', models.FileField(upload_to='geojsons')),
            ],
        ),
    ]
