# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-12 17:16
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('claim', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('layer_type', models.IntegerField(choices=[(0, 'Organization'), (1, 'District'), (2, 'Country')], default=0)),
                ('parse_file', models.BooleanField(default=False)),
                ('json_file', models.FileField(blank=True, null=True, upload_to='geojsons')),
                ('is_default', models.BooleanField(default=False)),
                ('zoom', models.IntegerField()),
                ('center', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Polygon',
            fields=[
                ('polygon_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('shape', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('centroid', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=800, null=True)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoinfo.Layer')),
                ('organizations', models.ManyToManyField(to='claim.Organization')),
            ],
        ),
        migrations.AddField(
            model_name='layer',
            name='higher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upper_level', to='geoinfo.Polygon'),
        ),
    ]
