# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-18 19:04
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoinfo', '0002_auto_20160210_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polygon',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
