# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-17 16:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoinfo', '0004_auto_20160315_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polygon',
            name='created',
        ),
        migrations.AddField(
            model_name='polygon',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 3, 17, 16, 6, 58, 376632)),
            preserve_default=False,
        ),
    ]
